# Generated by Django 4.1.3 on 2022-11-23 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='users.location'),
        ),
    ]
