# Generated by Django 4.1.3 on 2022-11-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
