# Generated by Django 4.1.3 on 2022-11-24 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ads_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='location',
        ),
    ]
