# Generated by Django 4.1.3 on 2022-11-27 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0003_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='owner',
            field=models.ForeignKey(choices=[('Owner', 'Owner'), ('Not owner', 'Not owner')], null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
