# Generated by Django 4.1.3 on 2022-11-27 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_selection_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection',
            name='owner',
        ),
    ]
