# Generated by Django 4.1.3 on 2022-11-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_remove_selection_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='owner',
            field=models.IntegerField(null=True),
        ),
    ]
